### ISSUE TITLE
Plugin doesn't work properly with JBrowse-1.14.2-dev

### ISSUE THREAD

**Issue by vaneet-lotay** [elsiklab/multibigwig#18]
When trying to load the multibigwig plugin into JBrowse-1.14.2-dev after running all the setup scripts, I can see the multibigwig track that I've set up but nothing is plotted.

Is it possible to post a fix for this so it works with the latest JBrowse versions?

Thank you,

Vaneet

**Comment by cmdcolin** [comment]
Hi Vaneet,

I can view the test data that I have setup in 1.14.2 so I'm not sure what the issue could be

For example what happens if you visit something like this?

localhost/jbrowse/?data=plugins/MultiBigWig/test/data


Do the test data tracks show up?

**Comment by vaneet-lotay** [comment]
When I view test data in JBrowse 1.14.2-dev on my browser, this is what I see:

![multibigwig_test](https://user-images.githubusercontent.com/40072920/41790507-05348c88-7610-11e8-8df4-f7df01507c27.png)

Have I forgot to configure something properly?  I have simply followed your instructions and inserted the "plugins" line in the tracklist.json of my track folder.

Vaneet

**Comment by vaneet-lotay** [comment]
Here's the java console while I was trying to load the test data in case you need to see it:

![mbw_console](https://user-images.githubusercontent.com/40072920/41790674-871d787c-7610-11e8-8ed4-0c838f4173a8.png)


Vaneet

**Comment by cmdcolin** [comment]
It looks like somehow HideTrackLabels is being included twice which causes the first large red error.

If possible I would make all your plugins included from one config file e.g. only jbrowse.conf or only trackList.json and not include some in one file and more in another, that can cause issues (specifically this issue https://github.com/GMOD/jbrowse/issues/897).


The thing about "cannot read property color" looks like the error from using an old version of MultiBigWig. I would recommend checking that you have the latest version of MultiBigWig in your plugins directory. Then re-run setup.sh

Sorry this issue seems to have caused you a bunch of trouble...hopefully it should not be too much more....

**Comment by maoyibo** [comment]
I unpacked MultiBigWig to plugins folder in JBrowse, and add "plugins": ["MultiBigWig"] to jbrowse_conf.json, then I rerun setup.sh
But when I visit ?data=plugins/MultiBigWig/test/data, The JBrowse show the default "Congratulations" Page, and I get error message: "plugin MultiBigWig not found, please ensure the plugin was included in this JBrowse build".  
How can I solve this problem?

**Comment by vaneet-lotay** [comment]
Hey Colin,

I re-uploaded the latest JBrowse package and obtained the latest code from GitHub for this plugin.  After trying some of the corrections you mentioned the MultiBigWig tracks seem to work fine.  I'm having trouble with another plugin so I still can't upgrade but hopefully I'll work out those issues soon.

Thanks,

Vaneet

**Comment by cmdcolin** [comment]
@maoyibo glad you got this figured out:). Let me know if there are any other problems

Same with you also vaneet! I guess I'll closer for now. I can add a note in the readme about using the dev version for plugin builds too
